version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: "{{image}}"
    container_name: "{{containerName}}"
    command: npm run start
    ports: {{#each ports}}
        - "{{this}}:{{this}}"{{/each}}
    links: {{#ifCond images.length '>' 0}}{{#each images}}
      - {{this}}{{/each}}{{/ifCond}}
    environment:
      NODE_ENV: "development"
      PORT: {{appPort}}{{#each envs as |value key|}}
      {{key}}: {{value}}{{/each}}{{#each images}}
  {{this}}:
    image: {{this}}
  {{/each}}
