#!/bin/bash
# Simple shell script to run application in dev mode
{{#ifCond language "===" "PYTHON"}}
python manage.py livereload
{{/ifCond}}
{{#ifCond language "===" "DJANGO"}}
python manage.py runserver --settings={{name}}.settings.development
{{/ifCond}}
