FROM ibmjava:8-sdk
MAINTAINER IBM Java engineering at IBM Cloud

{{#has buildType 'maven'}}
COPY target/{{appName}}-{{version}}.jar /app.jar
{{/has}}
{{#has buildType 'gradle'}}
COPY build/libs/{{appName}}-{{version}}.jar /app.jar
{{/has}}

ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]